import { expect, test } from '@playwright/test'

test('shareable region URL and development atlas route retain exact data', async ({ page }) => {
  await page.goto('/?disease=parkinson&metric=z_score&hemi=L&region=77&view=left')
  await expect(page.getByLabel('Details for Putamen L')).toContainText('AAL3v1:77')
  await expect(page.getByLabel('Disease', { exact: true })).toHaveValue('parkinson')
  await expect(page.getByLabel('Metric', { exact: true })).toHaveValue('z_score')
  await expect(page.getByRole('button', { name: 'Left' }).first()).toHaveClass(/active/)
  await expect.poll(() => new URL(page.url()).searchParams.get('region')).toBe('77')
  await page.getByLabel('Metric', { exact: true }).selectOption('anatomy')
  await expect.poll(() => new URL(page.url()).searchParams.get('metric')).toBe('anatomy')
  const devResponse = await page.goto('/dev/atlas-validation')
  expect(devResponse?.status()).toBe(200)
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await expect(page.getByText('ATLAS REGION VALIDATION', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Atlas region list').getByRole('button')).toHaveCount(138)
  const release = await page.request.get('/data/release.json')
  expect(release.ok()).toBeTruthy()
  expect((await release.json()).completed_diseases).toBe(10)
  const regionalCsv = await page.request.get('/data/parkinson_regional_enrichment.csv')
  expect(regionalCsv.ok()).toBeTruthy()
  expect((await regionalCsv.text()).split('\n').length).toBeGreaterThan(138)
})

test('capture public website sections', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Research screenshots use desktop viewport')
  test.setTimeout(150_000)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await page.waitForTimeout(1200)
  await page.locator('.hero').screenshot({ path: '../results/figures/web/web_home.png' })
  await page.getByLabel('Search brain region', { exact: true }).fill('Putamen L')
  await expect(page.getByLabel('Details for Putamen L')).toBeVisible()
  await page.getByLabel('Details for Putamen L').screenshot({ path: '../results/figures/web/web_region_detail.png' })
  await page.locator('#results').screenshot({ path: '../results/figures/web/web_results.png' })
  await page.locator('#methods').screenshot({ path: '../results/figures/web/web_methods.png' })
  await page.locator('#biology').screenshot({ path: '../results/figures/web/web_biology.png' })
})
