import { formatCount } from '../format'
import type { ProjectMetadata } from '../types'

export function ResearchSections({ metadata }: { metadata: ProjectMetadata }) {
  const counts = metadata.counts
  const validation = metadata.analysis.independent_validation
  return <main className="research-content">
    <section id="how" className="method-section public-intro"><p className="section-kicker">The question</p><h2>Why are some brain regions affected more than others?</h2><p className="lead">The brain is made of many regions, and those regions do not use the same genes in the same amounts. Diseases also have genetic risk factors involving particular genes. GENE2BRAIN brings these two pieces of information together to ask whether disease-linked genes are unusually active in particular parts of the healthy brain.</p><div className="concept-flow"><article><strong>Disease-linked genes</strong><span>+</span></article><article><strong>Healthy brain gene activity</strong><span>↓</span></article><article><strong>Regional molecular pattern</strong></article></div></section>
    <section id="before-after" className="before-after-section"><p className="section-kicker">A guided scientific story</p><h2>From genes to an interactive brain map</h2><div className="before-after-grid"><figure><img src="/images/web_brain_before.png" alt="Earlier block-like atlas diagnostic view" loading="lazy" /><figcaption>Start with disease-linked genes</figcaption></figure><figure><img src="/images/web_brain_after.png" alt="Folded human brain anatomy with mapped regions" loading="lazy" /><figcaption>Explore the signal across the brain</figcaption></figure></div></section>
    <section className="story-section" aria-labelledby="how-title"><p className="section-kicker">How GENE2BRAIN works</p><h2 id="how-title">Five questions guide the analysis</h2><div className="pipeline public-steps">{[['01','What genes are linked to the disease?','Large human genetic studies identify DNA changes associated with disease.'],['02','Where are those genes active?','The Allen Human Brain Atlas provides gene-activity measurements from human brain regions.'],['03','Where does the signal stand out?','We measure how strongly disease-linked genes are active in different regions.'],['04','Is the pattern unusual?','Matched random gene groups create a fair comparison with what chance would look like.'],['05','Does independent evidence agree?','Where suitable data exist, we compare the pattern with separate observations.']].map(([number,title,text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="data" className="data-methods-grid"><div><p className="section-kicker">Data &amp; sources</p><h2>What information is behind the map?</h2><p className="lead">The current Parkinson reference analysis combines human genetic evidence with gene activity measured across the healthy brain. These values are read from the verified project release.</p><dl className="data-list"><div><dt>Brain regions studied</dt><dd>{formatCount(counts.regions_analyzed)}</dd></div><div><dt>Healthy brain donors</dt><dd>{formatCount(counts.ahba_donors)}</dd></div><div><dt>Brain samples</dt><dd>{formatCount(counts.ahba_samples)}</dd></div><div><dt>Genes measured</dt><dd>{formatCount(counts.genes_analyzed)}</dd></div><div><dt>Parkinson-linked genes represented</dt><dd>{formatCount(counts.parkinson_genes_represented)}</dd></div><div><dt>Independent comparison</dt><dd>{validation.matched_validation_units > 0 ? 'Available' : 'Not available'}</dd></div></dl><div className="downloads"><a className="download-button" href="/data/parkinson_regional_enrichment.csv" download>Download regional results</a><a className="outline-button" href="/data/parkinson_atlas.json" download>Download project data</a><a className="outline-button" href="/data/release.json" download>Download release information</a></div></div><div id="methods"><p className="section-kicker">For researchers</p><h2>Data &amp; Methods</h2><p>Technical details are available here for researchers, students, and reviewers. GENE2BRAIN uses genetic studies, gene prioritization, the Allen Human Brain Atlas, matched gene-group comparisons, corrected significance, spatial sensitivity checks, independent validation, and biological interpretation.</p><details><summary>Open the technical methods</summary><h3>Expression and regional mapping</h3><p>AHBA microarray expression is processed into the 138-region AAL3 reference using the committed analysis outputs.</p><h3>Statistical comparison</h3><p>Observed regional scores are compared with matched random gene groups. Corrected probabilities and spatial sensitivity results are retained in downloadable tables.</p><h3>Independent evidence</h3><p>{validation.dataset} supplies {validation.phenotype.toLowerCase()}; the primary comparison used {formatCount(validation.matched_validation_units)} unique validation units.</p><h3>Limitations</h3><p>These are healthy-tissue expression associations, not pathology maps. They do not establish causality, disease origin, diagnosis, or individual prediction.</p></details></div></section>
    <section id="biology" className="biology-section"><p className="section-kicker">Biology</p><h2>What biology may be involved?</h2><p className="lead">Once regions stand out, we look at the genes contributing to their signal and ask which biological processes, pathways, and cell types are associated with them.</p><div className="biology-cards"><article><span>Genes</span><strong>{formatCount(counts.parkinson_genes_represented)}</strong><p>Disease-linked genes represented in the brain-expression data.</p></article><article><span>Biological processes</span><strong>{formatCount(metadata.analysis.biological_interpretation.go_significant_terms)}</strong><p>Gene Ontology results meeting the project’s correction rule.</p></article><article><span>Cell types</span><strong>{formatCount(metadata.analysis.biological_interpretation.cell_types_significant)}</strong><p>Associations with marker sets from human brain cell data.</p></article></div></section>
    <section id="about" className="about-section"><p className="section-kicker">About GENE2BRAIN</p><h2>From Genetic Risk to Spatial Brain Vulnerability</h2><p className="lead">GENE2BRAIN is an open, reproducible research visualization that combines disease genetics with gene activity across the healthy human brain.</p><p>Researcher name, affiliation, contact, and publication status remain pending confirmation for this release. No attribution or endorsement has been invented.</p><div className="author-profile" aria-label="Researcher profile pending confirmation"><h3>Researcher profile</h3><dl><div><dt>Name</dt><dd>Pending confirmation</dd></div><div><dt>Affiliation</dt><dd>Pending confirmation</dd></div><div><dt>Contact</dt><dd>Pending confirmation</dd></div></dl></div></section>
    <section id="citations" className="citations-section"><p className="section-kicker">Sources</p><h2>Citations &amp; provenance</h2><p>These sources contributed the measurements and methods used by GENE2BRAIN.</p><ol className="bibliography"><li><a href="https://human.brain-map.org/" target="_blank" rel="noreferrer">Allen Human Brain Atlas</a> — gene activity measured across the human brain.</li><li><a href="https://www.ebi.ac.uk/gwas/" target="_blank" rel="noreferrer">GWAS Catalog</a> — curated genetic associations.</li><li><a href="https://platform.opentargets.org/" target="_blank" rel="noreferrer">Open Targets</a> — evidence connecting genomic regions to candidate genes.</li><li><a href="https://doi.org/10.1016/j.neuroimage.2019.116189" target="_blank" rel="noreferrer">AAL3 atlas</a> — common anatomical region labels.</li></ol></section>
  </main>
}
